services:
    frontend:
      build:
        context: ./conduit-frontend
        args:
          API_URL: ${FRONTEND_API_URL}
      restart: on-failure:5
      ports:
        - "8282:80"
      depends_on:
        - backend
      networks:
        - backend_network

    backend:
      build:
        context: ./conduit-backend
      restart: on-failure:5
      ports:
        - "8281:8000"
      networks:
        - backend_network
      env_file:
        - .env
      volumes:
        - backend_db:/app/db
        - backend_media:/app/media


volumes:
    backend_db:
    backend_media:

networks:
  backend_network: