name: Docker Image CI
run-name: Deploy to ${{ github.event.head_commit.message }} by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with: 
        registry: ghcr.io 
        username: ${{ github.actor }} 
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Backend image
      uses: docker/build-push-action@v6
      with:
        context: ./conduit-backend
        file: ./conduit-backend/Dockerfile
        push: true
        tags: |
          ghcr.io/ensslinadrian/conduit-backend:latest
          ghcr.io/ensslinadrian/conduit-backend:${{ github.sha }}

    - name: Build Frontend image
      uses: docker/build-push-action@v6
      with:
        context: ./conduit-frontend
        file: ./conduit-frontend/Dockerfile
        push: true
        tags: |
          ghcr.io/ensslinadrian/conduit-frontend:latest
          ghcr.io/ensslinadrian/conduit-frontend:${{ github.sha }}
      
    - name: Create and Push .env
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cat << 'EOF' > ~/${{ secrets.PATH }}/.env
          ${{ secrets.ENV_FILE }}
          chmod 600 ~/${{ secrets.PATH }}/.env
          EOF

    - name: Copy docker-compose.yml to VM
      run: |
        scp -i <(echo "${{ secrets.KEY }}") \
        docker-compose.yml \
        ${{ secrets.USER }}@${{ secrets.HOST }}:~/${{ secrets.PATH }}/docker-compose.yml

    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          set -e
          cd ~/${{ secrets.PATH }}
          docker-compose pull
          docker-compose down
          docker-compose up -d --force-recreate
          docker image prune -f

