name: Github Action Demo
run-name: Deploy by @${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    # Step 1
      - name: Checkout repository
        uses: actions/checkout@v4

    # Step 2
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3
      - name: Create .env from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

    # Step 4
      - name: Build Docker images
        run: docker compose build

    # Step 5
      - name: Push Docker images
        run: docker compose push

    # Step 6
      - name: Copy compose.yaml and .env to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.yaml,.env"
          target: ${{ secrets.PATH }}

    # Step 7
      - name: Deploy on VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }} || exit 1
            docker compose pull
            docker compose up -d
